importing relevent libraries

In [13]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import statsmodels.api as sm

Loading the data file

In [14]:
data = pd.read_excel("C:/Users/ratnakar singh/Desktop/bUTLER_TRUCKING.xlsx")

In [15]:
data

Driving Assignmnet  x1 = Miles Traveled  x2 = Number of Deliveries  \
0                   1                  100                          4   
1                   2                   50                          3   
2                   3                  100                          4   
3                   4                  100                          2   
4                   5                   50                          2   
5                   6                   80                          2   
6                   7                   75                          3   
7                   8                   65                          4   
8                   9                   90                          3   
9                  10                   90                          2   

   y = Travel Time(hours)  
0                     9.3  
1                     4.8  
2                     8.9  
3                     6.5  
4                     4.2  
5                     6.2  
6                     7.4  
7                     6.0  
8                     7.6  
9                     6.1

modeling the data

In [5]:
x = data[['x1 = Miles Traveled']]
y = data['y = Travel Time(hours)'].values.reshape(-1,1)
reg = linear_model.LinearRegression()
reg.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

calculating coefficient

In [6]:
reg.coef_

array([[0.06782609]])

calculating intercept

In [7]:
reg.intercept_

array([1.27391304])

finding linear equation

In [8]:
print("The linear model is: y = {:.5} + {:.5}*Miles Traveled".format(reg.intercept_[0], reg.coef_[0][0]))

The linear model is: y = 1.2739 + 0.067826*Miles Traveled


In [10]:
x = data['x1 = Miles Traveled']
y = data['y = Travel Time(hours)']

x2 = sm.add_constant(x)
est = sm.OLS(y,x2)
est2 = est.fit()
print(est2.summary())

C:\temp\lib\site-packages\numpy\core\fromnumeric.py:2389: FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
  return ptp(axis=axis, out=out, **kwargs)


                              OLS Regression Results                              
Dep. Variable:     y = Travel Time(hours)   R-squared:                       0.664
Model:                                OLS   Adj. R-squared:                  0.622
Method:                     Least Squares   F-statistic:                     15.81
Date:                    Tue, 03 Sep 2019   Prob (F-statistic):            0.00408
Time:                            06:53:53   Log-Likelihood:                -13.092
No. Observations:                      10   AIC:                             30.18
Df Residuals:                           8   BIC:                             30.79
Df Model:                               1                                         
Covariance Type:                nonrobust                                         
                          coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------

C:\temp\lib\site-packages\scipy\stats\stats.py:1416: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=10
  "anyway, n=%i" % int(n))


In [28]:
x = data[['x1 = Miles Traveled', 'x2 = Number of Deliveries']]
y = data['y = Travel Time(hours)'].values.reshape(-1,1)
reg = linear_model.LinearRegression()
reg.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [29]:
reg.coef_

array([[0.0611346 , 0.92342537]])

In [30]:
reg.intercept_

array([-0.86870147])

In [31]:
print("The linear model is: y = {:.5} + {:.5}*Miles Traveled+ {:.5}*Number of Deliveries".format(reg.intercept_[0], reg.coef_[0][0],reg.coef_[0][1]))

The linear model is: y = -0.8687 + 0.061135*Miles Traveled+ 0.92343*Number of Deliveries


In [26]:
x = np.column_stack((data['x1 = Miles Traveled'],data['x2 = Number of Deliveries']))
y = data['y = Travel Time(hours)']

x2 = sm.add_constant(x)
est = sm.OLS(y,x2)
est2 = est.fit()
print(est2.summary())

                              OLS Regression Results                              
Dep. Variable:     y = Travel Time(hours)   R-squared:                       0.904
Model:                                OLS   Adj. R-squared:                  0.876
Method:                     Least Squares   F-statistic:                     32.88
Date:                    Tue, 03 Sep 2019   Prob (F-statistic):           0.000276
Time:                            07:08:33   Log-Likelihood:                -6.8398
No. Observations:                      10   AIC:                             19.68
Df Residuals:                           7   BIC:                             20.59
Df Model:                               2                                         
Covariance Type:                nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       

C:\temp\lib\site-packages\scipy\stats\stats.py:1416: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=10
  "anyway, n=%i" % int(n))
